### PR TITLE
[punjabi] New langauge

### PR DESCRIPTION
**Pull request by naveenvalecha**
Can we put this in when new language request will be merged in console https://github.com/hechoendrupal/DrupalConsole/pull/1892

### CODE REVIEW

**Comment by jmolivas** [comment]
@enzolutions: Did you saw this new language?

**Comment by jmolivas** [comment]
@naveenvalecha: Thanks for the PR.

**Comment by naveenvalecha** [comment]
Can we postpone this until the translation of the drupalconsole not finished as per my chat with @enzolutions

**Comment by jmolivas** [comment]
@naveenvalecha: Good to know the status and thanks for commenting.

**Comment by jmolivas** [comment]
Any news on this one @naveenvalecha @enzolutions ?

**Comment by enzolutions** [comment]
@naveenvalecha please complete the punjabi in the application and later we will work in documentation. also the folder command is auto generated in deploys

**Comment by enzolutions** [comment]
After we have 50% of the commands translated we will start with doc translation.

**Pull request closed without merging**
