### PR TITLE
Update available-commands.md

### PR DESCRIPTION
**Pull request by darol100**
I think we should have a note that you can't generate code if the module is enable. In this documentation page.  #54

### CODE REVIEW

**Comment by jmolivas** [comment]
@darol100 Yes you can generate code if the module is enable. I tried and this is an example:
* Generate module `example`
* Debug module (is disabled)
* Install module `example`
* Debug module (is enabled)
* Generate controller `DefaultController`

add-controller-installed-module

**Comment by darol100** [comment]
I try to run `drupal generate:form:config` and did not let me run into uninstall the module.

I did not even told me that needs to uninstall in order to add that functionality. I'm not sure if something wrong on my end or not. Did you try it out with `drupal generate:form:config` ? If you can duplicated the issue and is only on this command. We can open an issue on the DrupalConsole that it would prompt something like, In order to run this command your module needs to be uninstall.

**Comment by jmolivas** [comment]
Which version of console and drupal are you running you can confirm by running
```
drupal --version
drupal site:status
```

**Comment by darol100** [comment]
Drupal Console version 0.7.13

````````````````````
 System Info                                                                                                                             
 Drupal                    8.0.0-dev                                                                                                     
 Access to update.php      Protected                                                                                                     
 Configuration files       Protected                                                                                                     
 Cron maintenance tasks    Last run 6 seconds ago                                                                                        
 Database system           MySQL, MariaDB, Percona Server, or equivalent                                                                 
 Database system version   5.5.42                                                                                                        
 Database updates          Up to date                                                                                                    
 Drupal core update status <a href="/admin/reports/updates">Unknown release date (version 8.0.0-beta11 available)</a>                    
 File system               Writable (<em>public</em> download method)                                                                    
 GD library                bundled (2.1.0 compatible)                                                                                    
 GD library PNG support    bundled (2.1.0 compatible)                                                                                    
 Image toolkit             gd                                                                                                            
 Node Access Permissions   Disabled                                                                                                      
 PHP                       5.6.7 (<a href="/admin/reports/status/php">more information</a>)                                              
 PHP extensions            Enabled                                                                                                       
 PHP memory limit          128M                                                                                                          
 Search index progress     100% (0 remaining)                                                                                            
 Trusted Host Settings     Not enabled                                                                                                   
 Twig C extension          Not available                                                                                                 
 Unicode library           PHP Mbstring Extension                                                                                        
 Update notifications      Enabled                                                                                                       
 Upload progress           Not enabled                                                                                                   
 Web server                                                                                                                              
 Hash salt                 3gYETZ2nHppMlvCgmwrvpPdr8wXC9DTih8-kf4UyViJtwN850iOLvUJUcCzNf6DXsLz9glBqiA                                    
 Console version           0.7.13                                                                                                        
 Database connection                                                                                                                     
 Driver                    mysql                                                                                                         
 Host                      localhost                                                                                                     
 Database connection       d8.3                                                                                                          
 Port                      3306                                                                                                          
 Username                  d8.3                                                                                                          
 Password                  d8.3                                                                                                          
 Connection                mysql//d8.3:d8.3@localhost:3306/d8.3                                                                          
 Themes                                                                                                                                  
 theme_default             bartik                                                                                                        
 theme_admin               seven                                                                                                         
 Directories                                                                                                                             
 Site root directory       /Users/darrylnorris/Sites/d8/                                                                                 
 Site temporary directory  /Applications/MAMP/tmp/php                                                                                    
 Default theme directory   /core/themes/bartik                                                                                           
 Admin theme directory     /core/themes/seven                                                                                            
 Configuration                                                                                                                           
 Active config path        sites/default/files/config_UsoIllZIpqFJXcuLDDFvmW3-IIexiZv2DAR7mwf-Ai8PaFTWiFyrtT6KUTVih38ipPYLvPKHHw/active  
 Staging config path       sites/default/files/config_UsoIllZIpqFJXcuLDDFvmW3-IIexiZv2DAR7mwf-Ai8PaFTWiFyrtT6KUTVih38ipPYLvPKHHw/staging 

````````````````````

**Comment by jmolivas** [comment]
Than could be the issue the drupal version `8.0.0-dev`, we are currently supporting only the last beta.

**Comment by darol100** [comment]
Ohh interesting, let me check on a different site that use beta11 see if I still have the same issue. Should we report this or you would not be that worry about it?

**Comment by jmolivas** [comment]
We tried to chase dev releases when started the project but is kinda hard bacause of all of the changes and a lot of times those changes break console and even drupal :)

What we can do is create an issue to report anything breaking on dev to make sure we fix for the next Beta , RC release.

I see as checklist to task to fix kinda:
- [ ] Can't generate code if the module is enable.
- [ ] Service X is no longer available it was renamed as Service Y.

**Comment by darol100** [comment]
@jmolivas , For some reason I cant duplicated this issue. Not even in the environment that I was having problems with. I test it out on 8.0.0-dev and beta-11 and did not have a problem this time. Sorry about all this. I'm closing this issue.

**Comment by jmolivas** [comment]
Thank you for testing it.

**Pull request closed without merging**
