### PR TITLE
upd es lang 20180602

### PR DESCRIPTION
**Pull request by novia713**

### CODE REVIEW

**Comment by enzolutions** [comment]
@novia713 let's talk because for some reason the list of command available delete a lot of commands

**Comment by enzolutions** [comment]
@novia713 do you have any comment for my previous comment

**Comment by novia713** [comment]
i will review my commits and tell you something shortly

**Comment by novia713** [comment]
this PR can be dismissed, the new PRs of mine already include good translations for this @enzolutions

**Pull request closed without merging**
