### PR TITLE
More basic cleanup 2015 05 23

### PR DESCRIPTION
**Pull request by LowellMontgomery**
Minor fixes, including correction of typo in code-affecting “option” (autorization => authorization) and more minor cleanup of docs.

### CODE REVIEW

**Comment by jmolivas** [comment]
Thanks for the PR @LowellMontgomery 

I did some changes in between your changes and now there is a conflict, may you try to fix those conflicts and send the PR?

You will need  to run a `$ git fetch REMOTE_NAME` and then fix the conflicts, ping me if any help is needed.

**Comment by LowellMontgomery** [comment]
Happy to pitch in, @jmolivas :)

Anyway... Right... I needed to fix my configuration of the repository and didn't realize I didn't have your latest changes in my fork till later. Some of those changes I made on the flight, with no internet access. So, I've already fixed the conflict areas and am in the middle of a bit more clean-up of new text (some typo fixes, etc), as well as a bit of other revision that I think helps bring things further in the direction of "incremental improvement". I saw you had removed what I thought maybe didn't make sense for all commands (all the "default options" that might not actually make sense in most of the command calls, at all). I'd forgotten to ask about that, but had noticed they were part of the output in every call and might not always be applicable. I also like the revision direction you have taken. In the "contribution" section, I'm adding a new page to encourage contribution to THIS project, too, i.e. to helping the documentation process. I also wanted to ask what you have in mind for the "empty pages". I've added a bit to a couple of them, but others I wasn't sure what was appropriate or if they were even necessary (i.e.possibly redundant with other command documentation?)

Other thoughts: Some pages have non-standard heading hierarchy. It's probably better in this document, IMHO, to maintain standard heading hierarchy, i.e. not using H3 / H4 headings except as a sub-heading of corresponding "parent" H2 / H3 section. In blog posts intended for a feed (e.g. Planet Drupal), I might go straight to H3, due to filtering issues, but I don't think there is any pragmatic reason to do that in a document like this. OTOH, I will defer to your judgment and avoid making similar changes if I know you want to go with another standard, for whatever reason.

Anyway, I arrived back in Frankfurt yesterday; the week since the LA was mostly running around in the woods and hills, far from a network connection... so I'm ready to hit the ground running, now, and really try to get a good handle on this stuff, especially since mastering this will also give me ideas about how to build on Codeception. I should have a new commit or few a bit later this evening (or at least by *your* evening ... ;-) ). And I'll make them on this branch.

Cheers,

Lowell

**Comment by LowellMontgomery** [comment]
Now it should be better, I hope.

**Comment by jmolivas** [comment]
I like the idea of proper H2/H3 headings.

Related to empty pages not sure we added at the beginning just as a reminder of what we need to fill at this point I think is safe to remove and only add pages if there is some content on them.

**Comment by jmolivas** [comment]
Thanks for the PR @LowellMontgomery

**Comment by LowellMontgomery** [comment]
Okay… good. I will follow through with setting valid header hierarchies on any existing pages which need that fix... and add title attributes to links, etc (which helps SEO and also helps clarify link text, which might sometimes be ambiguous). I started adding link titles after I learned a bit of the more markup syntax and realized how simple it was.

I’ll go ahead and remove the empty pages or combine them into one page that encourages people to learn how to build their own custom commands, etc, using Drupal Console, but also encourages people to recognize useful improvements and learn how to contribute back anything that might be useful for other Drupal installations.

**Comment by jmolivas** [comment]
Awesome thanks

**Pull request merged**
