### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by danielnv18**
Just basic intrusions to run / develop with the console. Some got this information from jmolivas on twitter, other dmouse guide me on the Drupal Global Sprint and a little pieces by myself

If you guys think I should change something I'll do it but I think that part of this information should be part of the documentation

### CODE REVIEW

**Comment by jmolivas** [comment]
This looks great, ping me when you have time so we ca talk about this via IRC, chat or any other. to make some changes and add it to the documentation.

Thanks for helping us with the documentation adding this @danielnv18 ;)

**Comment by danielnv18** [comment]
@jmolivas Any week day at night it's good for me or weekends in general (sometimes I go out =D)

**Comment by jmolivas** [comment]
Let me know if you can later on today @danielnv18 and where can I ping you ?

**Comment by danielnv18** [comment]
@jmolivas [hangout](https://plus.google.com/u/0/+DanielNoyola) or [twitter](https://twitter.com/danielnv18) or just an [email](danielnv18@gmail.com)

**Pull request merged**
