### PR TITLE
Add list of Drupal Core cache names

### PR DESCRIPTION
**Pull request by MurzNN**
I suggest to add list of default cache names to documentation, because it is different from `drush`. Also will be good to provide list of available cache names in `drupal console` contextual help description.

### CODE REVIEW

**Comment by harold20** [comment]
Hi @MurzNN and thanks for the PR, but we manage the commands translations in another repository, The commands folder is autogenerated, Could you changes this here ?https://github.com/hechoendrupal/drupal-console-en/blob/master/translations/cache.rebuild.yml

**Comment by MurzNN** [comment]
I can't understand where to add this info, and how to write multiline texts. Can you please provide an example for other command, that have multi-line description with list of available options for arguments + description of it? Thanks!

**Comment by enzolutions** [comment]
@MurzNN  you could see and example at https://github.com/hechoendrupal/drupal-console-en/blob/master/translations/config.export.content.type.yml#L25

**Comment by MurzNN** [comment]
@enzolutions thanks for example, I create new pull request in right place: https://github.com/hechoendrupal/drupal-console-en/pull/243
Let's close this. Looking to PR id, with comment "404 Not found" :)

**Pull request closed without merging**
